#!/usr/bin/env sh
# SPDX-FileCopyrightText: 2022 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-Archive-packaging-exception

if test -n "${1-}"; then
  #echo 1>&2 "Dummy chown: ${*}"
  exit 0
fi

echo 1>&2 "chown: bad usage"
exit 1
